# Generated by Django 3.2.9 on 2022-03-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20220314_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='lugar_expedicion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='prioridad_urgente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='requiere_audiencia',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apellido_parterno_servidor_publico',
            field=models.CharField(default='?', max_length=100, verbose_name='Apellido Paterno del Servidor Público'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apelliod_materno_servidor_publico',
            field=models.CharField(default='-', max_length=100, verbose_name='Apellido Materno del Servidor Público'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='area_servidor_publico',
            field=models.CharField(default='-', max_length=255, verbose_name='Área del Servidor Público'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cargo_servidor_publico',
            field=models.CharField(default='-', max_length=255, verbose_name='Cargo del Servidor Público'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_servidor_publico',
            field=models.CharField(default='-', max_length=100, verbose_name='Nombre del Servidor Público'),
            preserve_default=False,
        ),
    ]
