# Generated by Django 3.2.9 on 2022-03-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('clave_lector', models.CharField(blank=True, max_length=18, null=True, verbose_name='Clave de Elector')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('organizacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organización')),
                ('puesto_organizacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puesto en la Organización')),
                ('correo_electronico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo Electrónico')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=10, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Interior')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('estado', models.CharField(default='Puebla', max_length=50, verbose_name='Estado')),
                ('colonia', models.CharField(max_length=150, verbose_name='Colonia')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.genero', verbose_name='Género')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
    ]
