# Generated by Django 3.2.9 on 2022-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitante',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='puesto_organizacion',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='rfc',
        ),
    ]
