# Generated by Django 3.2.9 on 2022-03-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Medios_Captacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_captacion', models.CharField(max_length=100, verbose_name='Medio de Captación')),
            ],
            options={
                'verbose_name': 'Medio de Captación',
                'verbose_name_plural': 'Medios de Captación',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dependencia', models.CharField(max_length=50, verbose_name='Tipo de Dependencia')),
            ],
            options={
                'verbose_name': 'Tipo de Dependencia',
                'verbose_name_plural': 'Tipos de Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_formato', models.CharField(max_length=50, verbose_name='Tipo de Formato')),
            ],
            options={
                'verbose_name': 'Tipo de Formato',
                'verbose_name_plural': 'Tipos de Formatos',
            },
        ),
        migrations.CreateModel(
            name='Canalizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=150, verbose_name='Dependencia')),
                ('titular', models.CharField(max_length=50, verbose_name='Titular')),
                ('tipo_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_dependencia', verbose_name='Tipo de Dependencia')),
                ('tipo_formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_formato', verbose_name='Tipo de Formato')),
            ],
            options={
                'verbose_name': 'Canalización',
                'verbose_name_plural': 'Canalizaciones',
            },
        ),
    ]
